[tools]
node = "26"
erlang = "29"

[tasks.dev]
run = "node src/main.js"

[tasks.test]
run = "node --test"

[tasks.bench]
run = "node --expose-gc bench/utf8.bench.js"

[tasks.gleam_app]
dir = "gleam_app/"
run = "gleam run"
