[tools]
node = "26"
erlang = "29"

[tasks.dev]
run = "node src/main.js"

[tasks.test]
run = "node --test"

[tasks.bench]
run = 'for f in bench/*.bench.js; do node --expose-gc "$f" || exit 1; done'

[tasks.gleam_app]
dir = "gleam_app/"
run = "gleam run"
