[tools]
node = "26"
erlang = "29"

[tasks.before]
run = "node src/before.js"

[tasks.after]
run = "node src/after.js"

[tasks.codepoints]
run = "node src/codepoints.js"

[tasks.test]
run = "node --test"

[tasks.bench]
run = 'for f in bench/*.bench.js; do echo "$f"; node --expose-gc "$f" || exit 1; done'

[tasks.gleam_app]
dir = "gleam_app/"
run = "gleam run"
